version: '3.8'

services:
  # Servizio PHP con Apache
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: corseapp_php
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=corseapp_user
      - MYSQL_PASSWORD=corseapp_password
      - MYSQL_DATABASE=f1_db
    networks:
      - corseapp_network

  # Servizio MySQL
  mysql:
    image: mysql:8.0
    container_name: corseapp_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/f1_db.sql:/docker-entrypoint-initdb.d/f1_db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=f1_db
      - MYSQL_USER=corseapp_user
      - MYSQL_PASSWORD=corseapp_password
    networks:
      - corseapp_network

  # Servizio phpMyAdmin (opzionale)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: corseapp_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=corseapp_user
      - PMA_PASSWORD=corseapp_password
    depends_on:
      - mysql
    networks:
      - corseapp_network

networks:
  corseapp_network:
    driver: bridge

volumes:
  mysql_data: